apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsim-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsim
  template:
    metadata:
      labels:
        app: devopsim
    spec:
      containers:
      - name: container-devopsim-server
        image: hadasregistry.azurecr.io/image-hadaspend-rachel-ukelson-1:1.0
        resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
        ports:  
        - containerPort: 3000
        securityContext: 
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: hadasregistry